name: Build and release for Windows

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          gcc

    - name: Checkout code
      uses: actions/checkout@v2.3.4

    - name: Install libsodium (Windows)
      run: |
        ./autogen.sh
        ./configure --prefix="$(pwd)/libsodium-win64"
        make
        make install
